# Generated by Django 5.1.1 on 2024-10-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'batteries',
            },
        ),
        migrations.CreateModel(
            name='IncomingPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'incoming_pallets',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='TigerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Events within Tiger',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='BatteryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.battery')),
            ],
            options={
                'db_table': 'battery_tests',
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='incoming_pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.incomingpallet'),
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('battery_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.batterytest')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiger.location')),
            ],
            options={
                'db_table': 'workstations',
            },
        ),
    ]
