# Generated by Django 5.1.1 on 2024-10-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstation',
            old_name='location_id',
            new_name='location',
        ),
    ]
