# Generated by Django 5.1.1 on 2024-10-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0002_rename_location_id_workstation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterytest',
            name='actual_serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='actual_voltage_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='cleaning_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='initial_image',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiger.location'),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='scanned_serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='scanned_voltage_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='serial_number_image',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='batterytest',
            name='voltage_reading_image',
            field=models.BinaryField(null=True),
        ),
    ]
