# Generated by Django 5.1.1 on 2024-10-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0003_batterytest_actual_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='battery_test',
        ),
        migrations.AddField(
            model_name='batterytest',
            name='workstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiger.workstation'),
        ),
    ]
