# Generated by Django 5.1.1 on 2024-10-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0005_workstation_current_pallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TigerEvent',
            new_name='Events',
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name': 'Battery'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
    ]
